# Generated by Django 2.0.5 on 2018-09-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_auto_20180904_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='tag',
            field=models.CharField(max_length=50),
        ),
    ]
