# Generated by Django 2.0.5 on 2018-09-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_auto_20180904_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.CharField(default='os', max_length=500),
        ),
    ]
