# Generated by Django 2.0.5 on 2018-09-05 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_remove_book_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(choices=[('', ''), ('COMPArch', 'CompArch'), ('Operating System', 'Operating System'), ('Networking', 'Networking'), ('Distributed System', 'Distributed System'), ('Machine Learning', 'Machine Learning'), ('Deep Learning', 'Deep Learning'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Algorithm', 'Algorithm'), ('Theoretical CS', 'Theoretical CS')], max_length=50)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.Book')),
            ],
        ),
    ]
