# Generated by Django 2.0.5 on 2018-09-05 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tags',
            new_name='tag',
        ),
    ]
